# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boke', '0006_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='fileImg',
            field=models.FileField(blank=True, null=True, upload_to='./img/'),
        ),
    ]
