# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-12 09:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boke', '0007_auto_20160808_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 12, 17, 12, 37, 113008)),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('U', '正常'), ('F', '禁用')], default='U', max_length=1),
        ),
    ]
