# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-15 01:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boke', '0008_auto_20160812_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 15, 9, 39, 40, 719148)),
        ),
    ]
